[tool.ruff]
line-length = 320

[tool.poetry]
name = "ormmysql"
version = "0.1.0"
description = ""
authors = ["p-hzamora <p.hzamora@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mysql-connector = "^2.2.9"
ruff = "^0.4.5"

[tool.poetry.group.test.dependencies]
pandas = "^2.2.2"
mysql-connector = "^2.2.9"
ruff = "^0.4.5"
python-decouple = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
